#!/bin/sh
# Covers scripts/dwm-session-launch.
#
# theme-env.sh is sourced once by autostart.sh at login, so anything spawned
# later inherits the cursor and Qt backend the session started with. The
# wrapper re-reads the file per launch. The assertion that proves it is the
# one where the file changes between two invocations.

# The probe commands quote their variables single-quoted on purpose: they must
# expand in the launched child, which is the whole thing under test, not here.
# shellcheck disable=SC2016

set -eu

# shellcheck source=tests/lib.sh
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)/lib.sh"

make_workspace

launcher=$repo/scripts/dwm-session-launch
assert_executable "$launcher"

home=$work/home
config_home=$home/.config
state_home=$home/.local/state
runtime=$work/run
mkdir -p "$config_home/lyona" "$state_home/lyona/appearance/toolkit" "$runtime"
theme_preview=$state_home/lyona/appearance/preview.current
toolkit_preview=$state_home/lyona/appearance/toolkit/preview.current
toolkit_failed=$state_home/lyona/appearance/toolkit/preview.failed
env_file=$config_home/lyona/theme-env.sh

write_env() {
	cat >"$env_file" <<EOF
# Auto-generated by theme-apply.sh -- do not edit manually.
export QT_QPA_PLATFORMTHEME=$1
export XCURSOR_THEME=$2
export XCURSOR_SIZE=$3
EOF
}

run_launcher() {
	HOME=$home XDG_CONFIG_HOME=$config_home XDG_STATE_HOME=$state_home \
		XDG_RUNTIME_DIR=$runtime "$launcher" "$@"
}

# ── The environment reaches the child ────────────────────────────────────

write_env qt6ct Capitaine-Cursors-White 32
first=$(run_launcher sh -c 'printf "%s|%s|%s" "$QT_QPA_PLATFORMTHEME" "$XCURSOR_THEME" "$XCURSOR_SIZE"')
assert_equals 'qt6ct|Capitaine-Cursors-White|32' "$first" \
	'the theme environment reaches the launched command'

# ── The staleness bug itself ─────────────────────────────────────────────
#
# Same wrapper process tree, changed file: the second launch must see the new
# values. Without the wrapper this is where a login-time environment goes
# stale.

write_env gtk3 Capitaine-Cursors 24
second=$(run_launcher sh -c 'printf "%s|%s|%s" "$QT_QPA_PLATFORMTHEME" "$XCURSOR_THEME" "$XCURSOR_SIZE"')
assert_equals 'gtk3|Capitaine-Cursors|24' "$second" \
	'a rewritten theme-env.sh is picked up on the next launch'
[ "$first" != "$second" ] || fail 'the two launches saw the same environment'

# ── A damaged record must never block a launch ───────────────────────────

check_still_launches() {
	printf '%s' "$1" >"$env_file"
	output=$(run_launcher sh -c 'printf "ran:%s" "${XCURSOR_THEME:-unset}"') ||
		fail "the wrapper refused to launch with: $2"
	case $output in
	ran:*) ;;
	*) fail "the wrapper did not exec the command with: $2" ;;
	esac
}

check_still_launches 'export XCURSOR_THEME=../evil
' 'a traversal cursor name'
check_still_launches 'export XCURSOR_THEME=Fine
export XCURSOR_THEME=Twice
' 'a duplicated key'
check_still_launches 'export SOMETHING_ELSE=1
' 'an unknown key'
check_still_launches 'export QT_QPA_PLATFORMTHEME=notabackend
' 'an unknown Qt backend'
check_still_launches '' 'an empty file'

# Oversized files are refused rather than parsed.
{
	printf '# Auto-generated by theme-apply.sh -- do not edit manually.\n'
	i=0
	while [ "$i" -lt 400 ]; do
		printf 'export XCURSOR_THEME=Padding%s\n' "$i"
		i=$((i + 1))
	done
} >"$env_file"
check_still_launches "$(cat "$env_file")" 'an oversized file'

# A symlinked record is refused: it is read on every launch, so it must not be
# redirectable.
write_env qt6ct Capitaine-Cursors-White 32
mv -fT -- "$env_file" "$work/real-env.sh"
ln -s "$work/real-env.sh" "$env_file"
symlinked=$(run_launcher sh -c 'printf "%s" "${XCURSOR_THEME:-unset}"')
assert_equals unset "$symlinked" 'a symlinked theme-env.sh is refused'
rm -f -- "$env_file"
mv -fT -- "$work/real-env.sh" "$env_file"

# ── Argument handling ────────────────────────────────────────────────────

set +e
run_launcher >/dev/null 2>&1
no_args_status=$?
set -e
assert_equals 2 "$no_args_status" 'no arguments is a usage error'

# The child's own exit status must survive the exec.
set +e
run_launcher sh -c 'exit 7' >/dev/null 2>&1
child_status=$?
set -e
assert_equals 7 "$child_status" 'the launched command owns the exit status'

# Arguments pass through untouched, including ones with spaces.
passed=$(run_launcher sh -c 'printf "%s" "$1"' _ 'two words')
assert_equals 'two words' "$passed" 'arguments reach the command intact'

# ── An unconfirmed preview must not be baked into a launch ───────────────
#
# During a preview theme-env.sh holds provisional values that a revert is
# about to undo. A process launched now keeps its environment for life, so it
# would outlive the revert wearing the previewed cursor. The wrapper leaves
# the environment it inherited alone instead, which is the last confirmed
# choice rather than an abandoned one.

write_env qt6ct Confirmed-Cursor 24
confirmed=$(run_launcher sh -c 'printf "%s|%s" "$QT_QPA_PLATFORMTHEME" "$XCURSOR_THEME"')
assert_equals 'qt6ct|Confirmed-Cursor' "$confirmed" 'the confirmed environment is read'

# theme-env.sh now describes a preview nobody has kept yet.
write_env gtk3 Provisional-Cursor 48

for marker in "$theme_preview" "$toolkit_preview" "$toolkit_failed"; do
	printf 'tok\n' >"$marker"
	quarantined=$(QT_QPA_PLATFORMTHEME=qt6ct XCURSOR_THEME=Confirmed-Cursor \
		run_launcher sh -c 'printf "%s|%s" "$QT_QPA_PLATFORMTHEME" "$XCURSOR_THEME"')
	assert_equals 'qt6ct|Confirmed-Cursor' "$quarantined" \
		"a pending preview at ${marker##*/} did not reach the launched command"
	rm -f -- "$marker"
done

# With nothing pending the provisional file is just the current file again.
kept=$(run_launcher sh -c 'printf "%s|%s" "$QT_QPA_PLATFORMTHEME" "$XCURSOR_THEME"')
assert_equals 'gtk3|Provisional-Cursor' "$kept" \
	'the environment was still quarantined after the preview was resolved'

# A launch must never be blocked by the quarantine check itself.
printf 'tok\n' >"$toolkit_preview"
output=$(run_launcher sh -c 'printf "ran:%s" "${XCURSOR_THEME:-unset}"') ||
	fail 'the wrapper refused to launch while a preview was pending'
case $output in
ran:*) ;;
*) fail 'the wrapper did not exec the command while a preview was pending' ;;
esac
rm -f -- "$toolkit_preview"

write_env qt6ct Capitaine-Cursors-White 32

# ── The callers reach it ─────────────────────────────────────────────────

for caller in dwm-quickshell-launcher dwm-quickshell-controlcenter \
	dwm-quickshell-network; do
	assert_contains "$repo/scripts/$caller" 'dwm-session-launch'
done
assert_contains "$repo/dwm.c" '"/dwm-session-launch"'
# Resolved beside the running binary, not through PATH, so a custom prefix
# cannot go stale between build and install.
assert_contains "$repo/dwm.c" '/proc/self/exe'

printf '%s\n' 'Session launch wrapper: PASS'
