"""Settings' system-management helper, behind scripts/dwm-system-management.

It reads system state for Settings and System Health, as bounded,
machine-readable snapshots and event streams: updates through PackageKit,
time, locale and regional settings, accounts, printers, repositories,
services, storage, security and hardware.

It also makes changes, each one confirmed by the user in Settings:
  - package updates, as PackageKit transactions (UpdatePackages), recorded in
    an operation journal so an interrupted update can be recovered;
  - time, time zone, NTP and locale changes through systemd's D-Bus services;
  - delegated launches of trusted administration tools.

It never runs as root. Privileged changes go through the D-Bus services,
which ask polkit.
"""

# The package is a read-only facade over its modules (Sync Sprint 12 S12-16):
# every name a module defines can be read here, for the tests and the bus
# fixtures, but a name is patched only on the module that defines it, which
# is where every module looks it up. Patching the package raises.

import sys
import types

import bisect
import contextlib
import ctypes
import errno
import fcntl
import hashlib
import io
import json
import os
import re
import selectors
import shlex
import shutil
import signal
import socket
import stat
import struct
import subprocess
import sys
import threading
import time
from dataclasses import dataclass, replace
from datetime import datetime, timezone
from typing import Callable, Iterable, Iterator, Mapping, Protocol, Sequence

from . import cli, delegated_tools, event_monitors, native_operations, operation_journal, packagekit, regional_settings, shared, snapshots, system_information, system_services, update_plans, user_accounts, watch_commands

# name -> the module that defines it
_DEFINED_IN = {
    'ACCOUNTS_NAME': 'shared',
    'ACCOUNTS_PATH': 'shared',
    'ACCOUNT_INTERFACE': 'shared',
    'ACCOUNT_LIMIT': 'shared',
    'ACCOUNT_LIST_BYTES': 'shared',
    'ACCOUNT_PROPERTIES': 'user_accounts',
    'ACCOUNT_PROPERTY_CONCURRENCY': 'user_accounts',
    'AccountEventMonitor': 'event_monitors',
    'AccountInventory': 'user_accounts',
    'AccountRead': 'user_accounts',
    'AccountRecord': 'user_accounts',
    'AuthenticatedEventMonitor': 'event_monitors',
    'BOOT_ID_PATTERN': 'shared',
    'CANCEL_GRACE_SECONDS': 'packagekit',
    'CUPS_READ_SECONDS': 'system_services',
    'CUPS_UNITS': 'shared',
    'CancelTargetUnavailable': 'operation_journal',
    'CupsRead': 'system_services',
    'CupsState': 'system_services',
    'DBUS_OBJECT_PATH': 'shared',
    'DELEGATED_ACTIONS': 'shared',
    'DELEGATED_TOOLS': 'delegated_tools',
    'ENCRYPTION_RECORDS': 'system_information',
    'EXIT_SUCCESS': 'shared',
    'FILESYSTEM_OUTPUT_BYTES': 'system_information',
    'FILESYSTEM_RECORDS': 'shared',
    'FIREWALL_UNITS': 'shared',
    'FilesystemInformation': 'system_information',
    'FilesystemRow': 'system_information',
    'FirewallUnitRead': 'system_services',
    'G_MAXUINT': 'shared',
    'HARDWARE_INFORMATION_FIELDS': 'shared',
    'HardwareRead': 'system_information',
    'INFORMATION_LOCAL_IDS': 'snapshots',
    'INFORMATION_MEMORY_KEYS': 'system_information',
    'INFORMATION_SECURITY_IDS': 'snapshots',
    'INFORMATION_UINT_MAX': 'system_information',
    'InformationSnapshotSources': 'snapshots',
    'InformationState': 'system_information',
    'JOURNAL_ACTIVE_ADMISSION_COMMITS': 'operation_journal',
    'JOURNAL_BOOT_ID_TEMPLATE': 'operation_journal',
    'JOURNAL_COMPONENT_MAX': 'operation_journal',
    'JOURNAL_CONTROL_ADMISSION_COMMITS': 'operation_journal',
    'JOURNAL_CURSOR_NAME': 'operation_journal',
    'JOURNAL_DATA_NAMES': 'operation_journal',
    'JOURNAL_DIRECTORY_SUFFIX': 'operation_journal',
    'JOURNAL_ERROR_CODES': 'shared',
    'JOURNAL_FILE_SIZE': 'operation_journal',
    'JOURNAL_FRAME_MAJOR': 'operation_journal',
    'JOURNAL_FRAME_MINOR': 'operation_journal',
    'JOURNAL_FRAME_SIZE': 'operation_journal',
    'JOURNAL_GENERATION_PATTERN': 'shared',
    'JOURNAL_LOCK_DEADLINE_SECONDS': 'operation_journal',
    'JOURNAL_MAGIC': 'operation_journal',
    'JOURNAL_NAMES': 'operation_journal',
    'JOURNAL_OPERATION_ACTION_KINDS': 'shared',
    'JOURNAL_OPERATION_ID_ATTEMPTS': 'operation_journal',
    'JOURNAL_OPERATION_ID_PATTERN': 'shared',
    'JOURNAL_OPERATION_STATES': 'operation_journal',
    'JOURNAL_OPERATION_TERMINAL_STATES': 'shared',
    'JOURNAL_PACKAGEKIT_PATH_PATTERN': 'shared',
    'JOURNAL_PATH_MAX': 'operation_journal',
    'JOURNAL_PAYLOAD_MAX': 'operation_journal',
    'JOURNAL_PAYLOAD_OFFSET': 'operation_journal',
    'JOURNAL_RESTART_ALL_CLEAR_SUFFIX': 'operation_journal',
    'JOURNAL_RESTART_ALL_CLEAR_TAIL': 'operation_journal',
    'JOURNAL_RESTART_SESSION_STRENGTH': 'shared',
    'JOURNAL_RESTART_SESSION_VALUES': 'operation_journal',
    'JOURNAL_RESTART_SYSTEM_STRENGTH': 'shared',
    'JOURNAL_RESTART_SYSTEM_VALUES': 'operation_journal',
    'JOURNAL_SEQUENCE_MAX': 'shared',
    'JOURNAL_SLOT_PATTERN': 'operation_journal',
    'JOURNAL_TERMINAL_COUNT': 'operation_journal',
    'JOURNAL_TIMESTAMP_PATTERN': 'operation_journal',
    'JOURNAL_TRANSITIONS': 'shared',
    'JournalAdmission': 'operation_journal',
    'JournalAdmissionError': 'operation_journal',
    'JournalCommitError': 'operation_journal',
    'JournalDescriptorSet': 'operation_journal',
    'JournalDirectoryChain': 'operation_journal',
    'JournalFileError': 'operation_journal',
    'JournalFrame': 'operation_journal',
    'JournalFrameError': 'operation_journal',
    'JournalHandoff': 'operation_journal',
    'JournalLayoutError': 'operation_journal',
    'JournalLockError': 'operation_journal',
    'JournalOperation': 'operation_journal',
    'JournalRecordError': 'operation_journal',
    'JournalRestart': 'operation_journal',
    'JournalState': 'operation_journal',
    'LocaleConfiguration': 'regional_settings',
    'MAX_LIST_BYTES': 'update_plans',
    'MAX_LIST_RECORDS': 'shared',
    'MAX_OPERATION_MISMATCH_SAMPLES': 'update_plans',
    'MAX_OPERATION_PROGRESS_RECORDS': 'update_plans',
    'MAX_TEXT_BYTES': 'shared',
    'MOUNT_ACTIONS': 'watch_commands',
    'MOUNT_MONITOR_EXEC': 'watch_commands',
    'NATIVE_SNAPSHOT_MINOR': 'snapshots',
    'NATIVE_WATCH_SECONDS': 'watch_commands',
    'NTP_SAMPLE_ERROR_CODES': 'regional_settings',
    'NTP_SAMPLE_STREAM_BYTES': 'regional_settings',
    'NativeJournalEvents': 'watch_commands',
    'NativeOperationOwner': 'native_operations',
    'NativeSnapshotSources': 'snapshots',
    'NtpRead': 'regional_settings',
    'NtpSample': 'regional_settings',
    'ObservedUpdateSummary': 'update_plans',
    'OperationProtocolError': 'update_plans',
    'OperationStream': 'update_plans',
    'PACKAGEKIT_INFO_PHASE': 'native_operations',
    'PACKAGEKIT_INTERFACE': 'shared',
    'PACKAGEKIT_NAME': 'shared',
    'PACKAGEKIT_PATH': 'shared',
    'PACKAGEKIT_STATUS_PHASE': 'packagekit',
    'PASSWORD_TERMINALS': 'delegated_tools',
    'PLAN_INFO': 'update_plans',
    'PROPERTIES_INTERFACE': 'shared',
    'PROTOCOL_MAJOR': 'shared',
    'PROTOCOL_MINOR': 'shared',
    'Package': 'update_plans',
    'PackageKitBackend': 'packagekit',
    'PackageKitMutation': 'native_operations',
    'PlanRow': 'update_plans',
    'READ_DEADLINE_SECONDS': 'packagekit',
    'REFRESH_AGE_DEADLINE_SECONDS': 'packagekit',
    'REGIONAL_CALLBACK_LIMIT': 'regional_settings',
    'REGIONAL_CHOICE_STREAM_BYTES': 'regional_settings',
    'REGIONAL_LOCALE_ARRAY_BYTES': 'regional_settings',
    'REGIONAL_LOCALE_COUNT': 'regional_settings',
    'REGIONAL_LOCALE_KEYS': 'regional_settings',
    'REGIONAL_LOCALE_MAX': 'regional_settings',
    'REGIONAL_LOCALE_OUTPUT_BYTES': 'regional_settings',
    'REGIONAL_MUTATION_SECONDS': 'regional_settings',
    'REGIONAL_PREVIEW_STREAM_BYTES': 'regional_settings',
    'REGIONAL_READ_REQUESTS': 'shared',
    'REGIONAL_READ_SECONDS': 'shared',
    'REGIONAL_TIMEZONE_BYTES': 'regional_settings',
    'REGIONAL_TIMEZONE_COUNT': 'regional_settings',
    'REGIONAL_TIMEZONE_MAX': 'regional_settings',
    'REGIONAL_TIME_PROPERTY_COUNT': 'shared',
    'REPOSITORY_MAX_BYTES': 'shared',
    'REPOSITORY_MAX_ROWS': 'shared',
    'REPOSITORY_READ_SECONDS': 'system_services',
    'RESTART_HEURISTIC_NAMES': 'update_plans',
    'RESTART_INFO': 'update_plans',
    'ROLE_REFRESH_CACHE': 'packagekit',
    'RecoveryEvidence': 'update_plans',
    'RecoverySnapshot': 'update_plans',
    'RegionalCommandInterrupted': 'native_operations',
    'RegionalEventMonitor': 'event_monitors',
    'RegionalMutation': 'regional_settings',
    'RegionalPreview': 'regional_settings',
    'RegionalRead': 'regional_settings',
    'RegionalTimeState': 'regional_settings',
    'RepositoryRead': 'system_services',
    'RepositoryRow': 'system_services',
    'SECURITY_FILES': 'system_information',
    'SNAPSHOT_MINOR': 'snapshots',
    'SYSTEMD_MANAGER': 'shared',
    'SYSTEMD_NAME': 'shared',
    'SYSTEMD_PATH': 'shared',
    'ServiceRead': 'shared',
    'SnapshotFailure': 'shared',
    'TIME_STATUS_STREAM_BYTES': 'regional_settings',
    'TRANSACTION_INTERFACE': 'shared',
    'TimeEventMonitor': 'event_monitors',
    'TransactionResult': 'update_plans',
    'UNIT_REPLY_BYTES': 'shared',
    'UNIT_REPLY_TYPE': 'system_services',
    'UNIT_STATE_TOKEN': 'shared',
    'UPDATE_INFO': 'update_plans',
    'UnitEventMonitor': 'event_monitors',
    'UnitState': 'system_services',
    'UpdateBackend': 'update_plans',
    'UpdateEventMonitor': 'event_monitors',
    'UpdateRow': 'update_plans',
    'WATCH_UNIT_SETS': 'shared',
    '_absolute_path_components': 'operation_journal',
    '_chmod_directory_descriptor': 'operation_journal',
    '_close_descriptors': 'operation_journal',
    '_commit_journal_file_unlocked': 'operation_journal',
    '_create_journal_path_unlocked': 'operation_journal',
    '_decode_journal_uint64': 'operation_journal',
    '_encode_journal_uint64': 'operation_journal',
    '_initial_journal_payloads': 'operation_journal',
    '_initialize_journal_file_unlocked': 'operation_journal',
    '_inspect_partial_journal_path_unlocked': 'operation_journal',
    '_is_all_clear_restart_payload': 'operation_journal',
    '_is_all_clear_restart_payload_prefix': 'operation_journal',
    '_is_safe_initial_fragment': 'operation_journal',
    '_is_safe_initial_path_fragment': 'operation_journal',
    '_is_safe_restart_initial_fragment': 'operation_journal',
    '_is_safe_restart_rewrite_fragment': 'operation_journal',
    '_journal_lock': 'operation_journal',
    '_journal_operation_fields': 'operation_journal',
    '_journal_payload_bytes': 'operation_journal',
    '_load_writable_journal_state': 'operation_journal',
    '_mkdir_private_directory': 'operation_journal',
    '_native_owner_descriptor': 'operation_journal',
    '_open_directory_component': 'operation_journal',
    '_open_partial_journal_path_unlocked': 'operation_journal',
    '_read_journal_file_unlocked': 'operation_journal',
    '_read_journal_image': 'operation_journal',
    '_read_partial_journal_image_unlocked': 'operation_journal',
    '_repair_empty_journal_path_mode_unlocked': 'operation_journal',
    '_require_exclusive_journal': 'operation_journal',
    '_restart_heuristic_hint': 'update_plans',
    '_restart_initial_header': 'operation_journal',
    '_retain_journal_files_unlocked': 'operation_journal',
    '_rewrite_initial_journal_path_unlocked': 'operation_journal',
    '_sync_directory_descriptor': 'operation_journal',
    '_try_native_owner_lock': 'operation_journal',
    '_unlock_native_owner': 'operation_journal',
    '_validate_directory_component': 'operation_journal',
    '_validate_initial_journal_path_unlocked': 'operation_journal',
    '_validate_initialized_journal_path_unlocked': 'operation_journal',
    '_validate_journal_descriptor': 'operation_journal',
    '_validate_journal_detail': 'operation_journal',
    '_validate_journal_lock_descriptor': 'operation_journal',
    '_validate_journal_path_identity': 'operation_journal',
    '_validate_journal_record_payload': 'operation_journal',
    '_validate_journal_timestamp': 'operation_journal',
    '_validate_partial_journal_path_identity': 'operation_journal',
    'account_object_path': 'user_accounts',
    'acknowledge_journal_handoff': 'operation_journal',
    'advance_journal_operation': 'operation_journal',
    'aggregate_restart': 'update_plans',
    'begin_journal_operation': 'operation_journal',
    'build_information_snapshot': 'snapshots',
    'build_managed_snapshot': 'snapshots',
    'build_native_snapshot': 'snapshots',
    'build_snapshot': 'snapshots',
    'cancel_journal_operation': 'watch_commands',
    'canonical_identity': 'update_plans',
    'classify_cups': 'system_services',
    'clean_text': 'shared',
    'close_locale_process': 'regional_settings',
    'commit_journal_file': 'operation_journal',
    'commit_writable_journal_path': 'operation_journal',
    'complete_journal_terminal': 'operation_journal',
    'confirmed_update_plan': 'update_plans',
    'control_journal_target': 'watch_commands',
    'control_output_writer': 'watch_commands',
    'decode_journal_cursor': 'operation_journal',
    'decode_journal_frame': 'operation_journal',
    'decode_journal_handoff': 'operation_journal',
    'decode_journal_operation': 'operation_journal',
    'decode_journal_restart': 'operation_journal',
    'decode_journal_state': 'operation_journal',
    'decode_regional_reply': 'regional_settings',
    'decode_repository_row': 'system_services',
    'decode_unit_state': 'system_services',
    'delegated_command': 'delegated_tools',
    'encode_journal_cursor': 'operation_journal',
    'encode_journal_frame': 'operation_journal',
    'encode_journal_handoff': 'operation_journal',
    'encode_journal_operation': 'operation_journal',
    'encode_journal_restart': 'operation_journal',
    'encoded_record_size': 'update_plans',
    'enforce_list_budget': 'update_plans',
    'finite_status_command': 'cli',
    'generate_journal_operation_id': 'operation_journal',
    'information_fields': 'system_information',
    'information_number': 'system_information',
    'information_text': 'system_information',
    'information_unknown': 'system_information',
    'initial_journal_image': 'operation_journal',
    'initialize_journal_file': 'operation_journal',
    'initialize_journal_layout': 'operation_journal',
    'journal_directory_path': 'operation_journal',
    'launch_delegated_tool': 'delegated_tools',
    'load_journal_state': 'operation_journal',
    'load_writable_journal_state': 'operation_journal',
    'locale_change_matches': 'regional_settings',
    'locale_process_status': 'regional_settings',
    'lock_writable_journal': 'operation_journal',
    'main': 'cli',
    'make_regional_preview': 'regional_settings',
    'match_update_history': 'update_plans',
    'mount_baseline_ready': 'watch_commands',
    'native_command': 'cli',
    'native_journal_owner_busy': 'operation_journal',
    'native_list_lines': 'snapshots',
    'normalize_plan': 'update_plans',
    'normalize_updates': 'update_plans',
    'ntp_sample_command': 'cli',
    'ntp_sample_output': 'regional_settings',
    'open_journal_directory': 'operation_journal',
    'open_journal_directory_chain': 'operation_journal',
    'open_writable_journal': 'operation_journal',
    'operation_control': 'cli',
    'package_display_fields': 'update_plans',
    'parse_cpu_information': 'system_information',
    'parse_filesystem_information': 'system_information',
    'parse_locale_configuration': 'regional_settings',
    'parse_memory_information': 'system_information',
    'parse_os_information': 'system_information',
    'parse_root_encryption': 'system_information',
    'parse_screen_lock': 'system_information',
    'parse_storage_json': 'system_information',
    'prepare_journal_admission': 'operation_journal',
    'prepare_locale_change': 'regional_settings',
    'prepare_timezone_change': 'regional_settings',
    'prune_journal_restart': 'operation_journal',
    'read_boot_id': 'update_plans',
    'read_filesystem_information': 'system_information',
    'read_firewall_status': 'system_services',
    'read_hardware_information': 'system_information',
    'read_information_process': 'system_information',
    'read_journal_file': 'operation_journal',
    'read_local_information': 'system_information',
    'read_locale_choices': 'regional_settings',
    'read_ntp_sample': 'regional_settings',
    'read_recovery_snapshot': 'update_plans',
    'read_regional_preview': 'regional_settings',
    'read_root_encryption': 'system_information',
    'read_screen_lock': 'system_information',
    'read_secure_boot_status': 'system_information',
    'read_security_bytes': 'system_information',
    'read_selinux_status': 'system_information',
    'read_storage_information': 'system_information',
    'read_terminal_selection': 'delegated_tools',
    'recover_journal_active': 'update_plans',
    'regional_choices': 'regional_settings',
    'regional_interruption_failure': 'native_operations',
    'regional_preflight_output': 'regional_settings',
    'regional_string_array': 'regional_settings',
    'reject_unadmitted_operation': 'update_plans',
    'replay_terminal_operation': 'update_plans',
    'require_locale_service_arguments': 'regional_settings',
    'require_regional_generation': 'regional_settings',
    'retain_native_journal_owner': 'operation_journal',
    'retain_writable_journal': 'operation_journal',
    'retained_journal_operation': 'operation_journal',
    'run_delegated_launch': 'native_operations',
    'run_interruptible_read': 'regional_settings',
    'run_interruptible_regional': 'native_operations',
    'run_packagekit_mutation': 'native_operations',
    'run_regional_mutation': 'native_operations',
    'select_journal_frame': 'operation_journal',
    'sibling_command': 'system_information',
    'snapshot_generation': 'update_plans',
    'stdout_writable': 'cli',
    'terminal_selection_environment': 'delegated_tools',
    'time_status_output': 'regional_settings',
    'trusted_delegated_executable': 'delegated_tools',
    'update_command': 'cli',
    'usage': 'cli',
    'validate_history_record': 'update_plans',
    'validate_journal_directory_chain': 'operation_journal',
    'validate_locale_catalog': 'regional_settings',
    'validate_locale_choices': 'regional_settings',
    'validate_locale_name': 'regional_settings',
    'validate_regional_argument': 'regional_settings',
    'validate_snapshot_size': 'snapshots',
    'validate_timezone_choices': 'regional_settings',
    'validate_timezone_name': 'regional_settings',
    'validate_transaction_list': 'update_plans',
    'watch_account_events': 'watch_commands',
    'watch_journal_operation': 'watch_commands',
    'watch_mount_events': 'watch_commands',
    'watch_native_journal_operation': 'watch_commands',
    'watch_regional_events': 'watch_commands',
    'watch_service_events': 'watch_commands',
    'watch_update_events': 'watch_commands',
}

for _name, _module in _DEFINED_IN.items():
    globals()[_name] = getattr(globals()[_module], _name)
del _name, _module


class _ReadOnlyFacade(types.ModuleType):
    def __setattr__(self, name, value):
        raise AttributeError(
            f"{name}: patch the module that defines it "
            f"(lyona_system_management.{_DEFINED_IN.get(name, '<module>')}), not the package")

    def __delattr__(self, name):
        self.__setattr__(name, None)


sys.modules[__name__].__class__ = _ReadOnlyFacade
